### ISSUE TITLE
Incorrect battery health

### ISSUE THREAD

**Issue by Neifab** [rurza/BatFi#34]
Hello there,

I've noticed an incorrect battery health pourcentage in the app. CoconutBattery tells me it's at 95,9 and BatFi at 100%.

I guess BatFi is taking the "official" macOS battery statut, maybe there is a way to put another one more accurate.

Best

![screenshot](https://github.com/rurza/BatFi/assets/76597174/b38a2343-a07a-422e-ac6f-6d856ba42cdc)

**Comment by rurza** [comment]
Hey! 
When the app was displaying calculated capacity, I was receiving a bunch of emails every week about it showing the "wrong" health. I'm not sure which one is actually "right," but because the OS consistently reports 100% for a new battery (while CoconutBattery might report values like 101% and then 95% two weeks later), I've decided to use the one provided by the OS.

**Comment by Neifab** [comment]
Thanks for the answer
